# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# 设置工作目录
WORKDIR /app

# 复制 package.json 和 package-lock.json
COPY package*.json ./

# 安装依赖，不运行 prepare 脚本
RUN npm install --ignore-scripts

# 复制源代码
COPY . .

# 使用 TypeScript 构建项目
RUN npm run build

# 设置环境变量
ENV NODE_ENV=production
# 设置超时时间为 5 分钟（Smithery 要求）
ENV TIMEOUT=300000

# 设置健康检查
HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 \
  CMD wget --no-verbose --tries=1 --spider http://localhost:3000/health || exit 1

# 使用 node 用户运行，而不是 root
USER node

# 设置入口命令运行 MCP 服务器
# 使用 --max-old-space-size=256 限制内存使用
CMD ["node", "--max-old-space-size=256", "dist/server.js"] 