# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# 设置工作目录
WORKDIR /app

# 复制 package.json 和 package-lock.json
COPY package*.json ./

# 安装依赖，不运行 prepare 脚本
RUN npm install --ignore-scripts

# 复制源代码
COPY . .

# 使用 TypeScript 构建项目
RUN npm run build

# 设置环境变量
ENV NODE_ENV=production
# 设置超时时间为 5 分钟（Smithery 的限制）
ENV TIMEOUT=300000

# 设置健康检查
HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 \
  CMD wget --no-verbose --tries=1 --spider http://localhost:${PORT:-3000}/health || exit 1

# 暴露默认端口（用于 WebSocket 连接）
EXPOSE ${PORT:-3000}

# 设置启动命令
CMD ["node", "dist/server.js"] 